MinsweeperWeb/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using MinesweeperClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer;
using MinsweeperWeb.Models;
using DataAccessLayer;
using Newtonsoft.Json;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using NLog;
using MinsweeperWeb.Utility;

namespace MinsweeperWeb.Controllers
{
    public class GameController : Controller
    {
        //Create an instance of the board obj with
        //easy difficulty and small size 
        public static Board gameBoard;

        //Business layer for game logic and rules 
        public static GameBusinessService gameRules;

        //Property to keep track of the game status 
        public static string gameStatus;

        //Property to keep track of the current user
        public static string userName;

        //Game properties
        public static int clicks;
        
        public IActionResult Index()
        {
            //Create an instance of the GameBoardViewModel
            GameBoardViewModel game = new GameBoardViewModel();

            //Instantiate the game business class
            gameRules = new GameBusinessService();

            //Setup the game board 
            gameBoard = gameRules.SetupGame(10, gameBoard);
            gameStatus = "In Progress";
            MyLogger.GetInstance().Info("Session - " + HttpContext.Session.GetString("username"));
            //If the session is not empty - user logged in
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("username")))
            {
                //Grab their username
                userName = HttpContext.Session.GetString("username");
            }
            else
            {
                userName = "";
            }
                
           
            game.GameBoard = gameBoard;
            game.numOfClick = clicks;
            game.UserName = userName;

            //Pass the GameBoardViewModel with the next view
            return View("Index", game);
        }

        //Manage the button click on he grid - left click
        public IActionResult LeftClickContinueGame(int mineID)
        {
            //Update the click property 
            clicks++;

            //Play the move and record outcome
            gameStatus = gameRules.PlayMove(gameBoard, mineID);

            //If the player revealed all mine
            if (gameStatus == "Won")
            {
                //Setup the ViewBags for message
                ViewBag.Message = "Congrats you won!!";

                //End the game and make our game view model
                gameBoard = gameRules.EndGame(gameBoard);
                GameBoardViewModel game = new GameBoardViewModel(gameBoard, gameBoard.GrabCellFromGrid(mineID));
                game.UserName = userName;
                game.EndGame = gameStatus;
                game.numOfClick = clicks;


                return PartialView("EndGame", game);
            }

            //The player clicked on a mine
            else if (gameStatus == "Lost")
            {
                //Setup the ViewBags for message
                ViewBag.Message = "You lost. Let's play again!";

                //End the game and make our game view model
                gameBoard = gameRules.EndGame(gameBoard);
                GameBoardViewModel game = new GameBoardViewModel(gameBoard, gameBoard.GrabCellFromGrid(mineID));
                game.UserName = userName;
                game.EndGame = gameStatus;
                game.numOfClick = clicks;

                return PartialView("EndGame", game);
            }
            //Player has not won or lost - still playing
            else 
            {
                //Create our game view model
                GameBoardViewModel game = new GameBoardViewModel(gameBoard, gameBoard.GrabCellFromGrid(mineID));
                game.UserName = userName;
                game.EndGame = gameStatus;
                game.numOfClick = clicks;

                return PartialView("InProgressGame", game);
            }
        }

        //Manage the right button click on he grid 
        public IActionResult RightClickContinueGame(int mineID)
        {
            //Update the click property 
            clicks++;

            //Play the move and record outcome
            gameStatus = gameRules.FlagMine(gameBoard, mineID);

            //If player flagged all bombs
            if (gameStatus == "Won")
            {
                //Setup the ViewBags for message
                ViewBag.Message = "Congrats you won!!";

                //Create our game view model
                gameBoard = gameRules.EndGame(gameBoard);
                GameBoardViewModel game = new GameBoardViewModel(gameBoard, gameBoard.GrabCellFromGrid(mineID));
                game.UserName = userName;
                game.EndGame = gameStatus;
                game.numOfClick = clicks;

                return PartialView("EndGame", game);
            }

            else 
            {
                //Create our game view model
                GameBoardViewModel game = new GameBoardViewModel(gameBoard, gameBoard.GrabCellFromGrid(mineID));
                game.UserName = userName;
                game.EndGame = gameStatus;
                game.numOfClick = clicks;

                return PartialView("InProgressGame", game);
            }
        }

        //Manages request when a player wants to play new game
        public IActionResult PlayAgain()
        {
            //Reset the click proprty and gamestatus
            clicks = 0;
            gameStatus = "In Progress";

            //Setup the game board 
            gameBoard = gameRules.SetupGame(10, gameBoard);
            
            
            //Create game board view model
            GameBoardViewModel game = new GameBoardViewModel();
            game.GameBoard = gameBoard;
            game.UserName = userName;
            game.numOfClick = clicks;

            return View("Index", game);
        }

        //Manages when player saves game 
        public IActionResult OnSave(int seconds)
        {
            //Using JSON object seralization - turn our gameboard into a string for database
            string gameString = JsonConvert.SerializeObject(gameBoard);

            //Create new instance of GameBusinessService
            GameDataBusinessService gameBusiness = new GameDataBusinessService();

            //Use session to grab user
            int userID = (int)HttpContext.Session.GetInt32("userID");

            //Make an instance of Game data object 
            Game gameDataObj = new(gameString, seconds, clicks, userID);
            
            //Save game
            bool success = gameBusiness.SaveGame(gameDataObj);

            //Create game board view model
            GameBoardViewModel game = new GameBoardViewModel(gameBoard, gameBoard.GrabCellFromGrid(1));
            game.UserName = userName;
            game.EndGame = gameStatus;
            game.numOfClick = clicks;

            return PartialView("InProgressGame", game); 
        }


        //Mamages when a player loads their last save from the database
        public IActionResult OnLoad()
        {
            //Create new instance of GameBusinessService
            GameDataBusinessService gameDataBusiness = new GameDataBusinessService();

            //Use session to grab user
            int userID = (int)HttpContext.Session.GetInt32("userID");

            //Load the game
            Game gameObject = gameDataBusiness.LoadGame(userID);

            //Using seralization and object casting convert the boardstring 
            //from the database into a game board object
            gameBoard = JsonConvert.DeserializeObject<Board>(gameObject.boardString);

            //Debug
            Debug.WriteLine(JsonConvert.DeserializeObject<Board>(gameObject.boardString));

            //Create game view model
            GameBoardViewModel game = new GameBoardViewModel();
            game.GameBoard = gameBoard;
            game.UserName = userName;
            game.EndGame = gameStatus;
            game.Mine = gameBoard.GrabCellFromGrid(1);
            game.numOfClick = gameObject.numOfClicks;
            game.loadedSeconds = gameObject.seconds;

            //Debug the seconds
            Debug.WriteLine(game.loadedSeconds);

            return PartialView("InProgressGame", game);
        }

        /// <summary>
        /// Loads one save using gameStateID
        /// </summary>
        /// <param name="gameStateID"></param>
        /// <returns></returns>
        public IActionResult LoadOneGame(int gameStateID)
        {

            ///Create new instance of GameBusinessService
            GameDataBusinessService gameDataBusiness = new GameDataBusinessService();

            //Use session to grab user
            //If the session is not empty - user logged in
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("username")))
            {
                //Grab their username
                userName = HttpContext.Session.GetString("username");
            }

            //Load the game
            Game gameObject = gameDataBusiness.LoadOneGame(Convert.ToInt32(gameStateID));

            //Using seralization and object casting convert the boardstring 
            //from the database into a game board object
            gameBoard = JsonConvert.DeserializeObject<Board>(gameObject.boardString);

            //Create game view model
            GameBoardViewModel game = new GameBoardViewModel();
            game.GameBoard = gameBoard;
            game.UserName = userName;
            game.EndGame = gameStatus;
            game.Mine = gameBoard.GrabCellFromGrid(1);
            game.numOfClick = gameObject.numOfClicks;
            game.loadedSeconds = gameObject.seconds;


            return View("LoadedGame", game);
        }

        //THIS CAN BE AN API
        public int getLoadedSeconds()
        {

MinsweeperWeb/Controllers/LoginController.cs
using BusinessLayer;
using DataAccessLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MinesweeperClasses;
using MinsweeperWeb.Models;
using MinsweeperWeb.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MinsweeperWeb.Controllers
{
    public class LoginController : Controller
    {
        //Accessing the user model with the DAL 
        UserData userDAO = new UserData();

        //Create an instance of the board obj with
        //easy difficulty and small size 
        public static Board gameBoard;

        //Business layer for game logic and rules 
        public static GameBusinessService gameRules;

        //Logger dependecy injection 
        public ILogger logger { get; set; }

        //Constructor with injected ILogger
        public LoginController(ILogger logger)
        {
            this.logger = logger;
        }

        //View to the home of Login - login form 
        public IActionResult Index()
        {
            return View();
        }
        
        /// <summary>
        /// POST request for user to log in
        /// </summary>
        /// <param name="auth"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(Authentication auth)
        {
            logger.Info("Processing a login attempt.");
            logger.Info("Attempting Login- Username: " + auth.Username + " Password: " + auth.Password);

            //if the auth is valid - take to login successful 
            if (userDAO.LoginUser(auth) > 0)
            {
                logger.Info("Login Successful with- Username: " + auth.Username + " Password: " + auth.Password);
                int userID = userDAO.LoginUser(auth);
                UserData userData = new UserData();
                User user = userData.GrabUserByID(userID);

                //Sessions start 
                HttpContext.Session.SetString("username", user.Username);
                HttpContext.Session.SetInt32("userID", userID);

                return RedirectToAction("Index", "Game");
            }
            //User not logged in 
            else
            {
                logger.Warning("Login Faliure with- Username: " + auth.Username + " Password: " + auth.Password);
                //Remove all sessions that hold credentials 
                HttpContext.Session.Remove("username");
                HttpContext.Session.Remove("userID");

                return View("Views/Login/LoginFail.cshtml");
            }

        }

        public IActionResult Logout()
        {
            MyLogger.GetInstance().Info("Processing a logout attempt for - " +
                HttpContext.Session.GetString("username"));

            //Remove all sessions that hold credentials
            //HttpContext.Session.SetString("username", String.Empty);
            //HttpContext.Session.SetInt32("userID", 0);

            //Remove all sessions that hold credentials 
            HttpContext.Session.Remove("username");
            HttpContext.Session.Remove("userID");

            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("username")) &&
                (HttpContext.Session.GetString("userID") != null))
                logger.Warning("Failre removal of session - " + String.IsNullOrEmpty(HttpContext.Session.GetString("username")) + " at logout");
            else
                logger.Info("Sucess removal of session at logout");
                
            return View("Index");
        }
    }
}

MinsweeperWeb/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using MinsweeperWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer;
using Microsoft.AspNetCore.Http;
using MinsweeperWeb.Utility;

namespace MinsweeperWeb.Controllers
{
    public class RegisterController : Controller
    {
        //Accessing the user model with the DAL 
        UserData userDAO = new UserData();

        //Logger dependecy injection 
        public ILogger logger { get; set; }

        //Constructor with injected ILogger
        public RegisterController(ILogger logger)
        {
            this.logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(User user)
        {
            logger.Info("Registration attempt.");
            bool isRegistered = false;

            isRegistered = userDAO.RegisterUser(user);
            if (isRegistered)
            {
                logger.Info("Registation attempt successful for: " + user.Username);

                //Log the user in 
                Authentication auth = new Authentication();
                auth.Username = user.Username;
                auth.Password = user.Password;
                int userID = userDAO.LoginUser(auth);

                //Start the user sessions
                HttpContext.Session.SetString("username", user.Username);
                HttpContext.Session.SetInt32("userID", userID);

                if (!String.IsNullOrEmpty(HttpContext.Session.GetString("username")) &&
                (HttpContext.Session.GetString("userID") != null))
                    logger.Info("Successfully created session for - " + HttpContext.Session.GetString("username") + " at registration");
                else
                    logger.Warning("Failed to create session for " + user.Username);

                return View("Views/Register/RegisterSuccess.cshtml", user);
            }
            else
            {
                logger.Warning("Registation attempt failure for: " + user.Username);
                return View("Views/Register/RegisterFail.cshtml");
            }

        }
    }
}

MinsweeperWeb/Controllers/SavesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer;
using BusinessLayer;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using MinesweeperClasses;
using System.Diagnostics;
using MinsweeperWeb.Models;

namespace MinsweeperWeb.Controllers
{
    public class SavesController : Controller
    {
        /// <summary>
        /// Index for Saves Page 
        /// Only accessible to users logged in 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [CustomAuthorization]
        public IActionResult Index()
        {
            GameDataBusinessService gameData = new GameDataBusinessService();
            //Grab userID from session
            int userID = (int)HttpContext.Session.GetInt32("userID");

            return View(gameData.AllGamesForUser(userID));
        }

        /// <summary>
        /// Redirects back to GmeController to load game
        /// </summary>
        /// <param name="gameStateID"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Load(int gameStateID)
        {
            return RedirectToAction("LoadOneGame", "Game", gameStateID);
        }

        /// <summary>
        /// Deletes from the saves
        /// </summary>
        /// <param name="gameStateID"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Delete(int gameStateID)
        {
            GameDataBusinessService gameData = new GameDataBusinessService();
            gameData.DeleteSave(gameStateID);
            int userID = (int)HttpContext.Session.GetInt32("userID");
            return View("Index", gameData.AllGamesForUser(userID));
        }


    }
}

MinsweeperWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BombSquad</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-info border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BombSquad</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (String.IsNullOrEmpty(Context.Session.GetString("username")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Index">Register</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }
                        else
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                        @if (!String.IsNullOrEmpty(Context.Session.GetString("username")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Saves" asp-action="Index">Saves</a>
                            </li>

                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Play</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="text-align:center;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BombSquad - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MinsweeperWeb/Views/Shared/_NavBar.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/NavBar.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

    <div class="text-center">
        <h1 class="display-6">BombSquad</h1>
        <br />
        <img class="game-button-image" src="~/img/BombCell.png" />
    </div>

    <div class="sidenav">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BombSquad</a>
        @if (String.IsNullOrEmpty(Context.Session.GetString("username")))
        {
            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Index">Register</a>

            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>

        }
        else
        {

            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
        }
        @if (!String.IsNullOrEmpty(Context.Session.GetString("username")))
        {
            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Play</a>
            <a class="nav-link text-dark" asp-area="" asp-controller="Saves" asp-action="Index">Saves</a>

        }

    </div>
</body>
</html>